
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfkqbqehwvajhfinfqwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indma3FicWVod3ZhamhmaW5mcXdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MTQ5MjksImV4cCI6MjA1ODk5MDkyOX0.PQZXCH0L58c4PZBPYfIMJy2TUaQWtsI1Uata9bAvJ5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
