
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivayxniztnyojgusdwpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2YXl4bml6dG55b2pndXNkd3B0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMTg1NjIsImV4cCI6MjA1ODg5NDU2Mn0.L4D_o398EXNqbaelamr8l0NqgCFgARIGYILMeEn-aqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
